import { migratedWixDocumentUrl } from "@/lib/wix-document-url";
import { migratedWixMediaUrl } from "@/lib/wix-media-url";

type Node = { type?: string; nodes?: Node[]; textData?: { text?: string; decorations?: Array<{ type?: string; linkData?: { link?: { url?: string } } }> }; paragraphData?: { textStyle?: { textAlignment?: string } }; headingData?: { level?: number }; imageData?: { image?: { src?: { id?: string } } }; videoData?: { video?: { src?: { id?: string } }; title?: string }; fileData?: { name?: string; path?: string; src?: { id?: string } } };
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
function mediaSrc(id = "") { return migratedWixMediaUrl(id) || ""; }
function inline(nodes: Node[] = []) { return nodes.map((node) => { let value = escape(node.textData?.text || "").replace(/\r?\n/g, "<br>"); const decorations = node.textData?.decorations || []; if (decorations.some((item) => item.type === "BOLD")) value = `<strong>${value}</strong>`; if (decorations.some((item) => item.type === "ITALIC")) value = `<em>${value}</em>`; if (decorations.some((item) => item.type === "UNDERLINE")) value = `<u>${value}</u>`; const url = decorations.find((item) => item.type === "LINK")?.linkData?.link?.url; if (url) value = `<a href="${escape(migratedWixDocumentUrl(url))}">${value}</a>`; return value; }).join(""); }
function render(node: Node): string { const children = inline(node.nodes); switch (node.type) { case "PARAGRAPH": return `<p>${children || "<br>"}</p>`; case "HEADING": { const level = Math.min(3, Math.max(2, node.headingData?.level || 2)); return `<h${level}>${children}</h${level}>`; } case "IMAGE": { const src = mediaSrc(node.imageData?.image?.src?.id); return src ? `<img src="${escape(src)}" alt="" />` : ""; } case "VIDEO": { const src = mediaSrc(node.videoData?.video?.src?.id); return src ? `<video src="${escape(src)}" controls></video>` : ""; } case "FILE": { const source = migratedWixDocumentUrl(node.fileData?.path || node.fileData?.src?.id || ""); return source ? `<p><a href="${escape(source)}">${escape(node.fileData?.name || "Open attachment")}</a></p>` : ""; } default: return (node.nodes || []).map(render).join(""); } }
export function newsRichContentToHtml(document: unknown, fallback = "") { const nodes = (document as { nodes?: Node[] } | null)?.nodes; if (!nodes?.length) return fallback.split(/\n{2,}/).map((line) => `<p>${escape(line).replace(/\r?\n/g, "<br>")}</p>`).join(""); return nodes.map(render).join(""); }
