import portraitCutouts from "@/data/portrait-cutouts.json";

const cutoutPortraits = new Set<string>(portraitCutouts);

/**
 * True when the portrait is a subject cut out of its background rather than a
 * full-bleed photograph. Cutouts are placed on a white plate and contained;
 * photographs fill and crop their frame.
 *
 * The list is generated by `npm run detect:cutouts`, which decodes each
 * portrait's alpha channel. File extension is not a usable signal — most PNG
 * portraits here are opaque photos that merely carry an unused alpha channel.
 */
export function isCutoutPortrait(imageSrc: string) {
  return cutoutPortraits.has(imageSrc);
}

/** Directory-relative portrait filenames resolve against their gallery; absolute ones pass through. */
export function resolvePortraitSrc(imageFilename: string, imageDirectory: string) {
  return imageFilename.startsWith("/") || /^https?:\/\//i.test(imageFilename)
    ? imageFilename
    : `${imageDirectory}/${imageFilename}`;
}

/** The local placeholder used when a doctor has no uploaded portrait. */
export function isMissingPortrait(imageSrc: string | null | undefined) {
  if (!imageSrc) return true;

  // Wix also exposes the stock silhouette as media files. Keep these IDs in
  // the fallback path so an old imported record cannot make the silhouette
  // reappear after a Supabase sync.
  const normalized = imageSrc.toLowerCase();
  return (
    normalized.includes("profile-placeholder") ||
    normalized.includes("a4276d_69bbca18197246b2ac6a61de719068d8") ||
    normalized.includes("bba2f0_5261ce9822014627ae6bdfa1955568f5")
  );
}
